const CONTRACT_TYPE = {
  CULTIVATION: "CULTIVATION",
  HARVEST_SALE: "HARVEST_SALE",
};

const CONTRACT_STATUS = {
  DRAFT: "DRAFT",
  SENT: "SENT",
  NEGOTIATING: "NEGOTIATING",
  ACCEPTED: "ACCEPTED",
  PENDING_SIGNATURE: "PENDING_SIGNATURE",
  AWAITING_BUYER_SIGNATURE: "AWAITING_BUYER_SIGNATURE",
  ACTIVE: "ACTIVE",

  HARVEST_COMPLETED: "HARVEST_COMPLETED",

  DELIVERY_IN_PROGRESS: "DELIVERY_IN_PROGRESS",
  DELIVERY_COMPLETED: "DELIVERY_COMPLETED",

  FINAL_PAYMENT_PENDING: "FINAL_PAYMENT_PENDING",

  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

module.exports = {
  CONTRACT_TYPE,
  CONTRACT_STATUS,
};
